# <a id='toc1_'></a>[NumPy Tutorial](#toc0_)
---

**Table of contents**<a id='toc0_'></a>    
- [NumPy Tutorial](#toc1_)    
  - [(1) NumPy 배열 생성](#toc1_1_)    
  - [(2) Numpy 배열 초기화](#toc1_2_)    
  - [(3) NumPy 배열 크기 변형](#toc1_3_)    
  - [(4) NumPy 배열 데이터 추출하기](#toc1_4_)    
    - [인덱싱(Indexing)](#toc1_4_1_)    
    - [슬라이싱(Slicing)](#toc1_4_2_)    
  - [(5) NumPy 선형 대수 기본 연산](#toc1_5_)    
    - [행렬 내적(행렬 곱)](#toc1_5_1_)    
    - [전치 행렬](#toc1_5_2_)    
  - [(6) NumPy 기술 통계](#toc1_6_)    
    - [배열 데이터 개수](#toc1_6_1_)    
    - [평균, 분산, 표준편차](#toc1_6_2_)    
    - [최댓값, 최솟값, 중앙값](#toc1_6_3_)    
    - [사분위수](#toc1_6_4_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=1
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

---

## <a id='toc1_1_'></a>[(1) NumPy 배열 생성](#toc0_)

In [1]:
import numpy as np

In [3]:
# NumPy 배열 생성 및 타입, 크기 확인
a1 = np.array([1, 2, 3])
print(a1)
print("array1 type : ", type(a1))
print("array1 shape : ", a1.shape)

print()

a2 = np.array([[1, 2, 3], [4, 5, 6]])
print(a2)
print("array2 type : ", type(a2))
print("array2 shape : ", a2.shape)

print()

a3 = np.array([[1, 2, 3]])
print(a3)
print("array3 type : ", type(a3))
print("array3 shape : ", a3.shape)

[1 2 3]
array1 type :  <class 'numpy.ndarray'>
array1 shape :  (3,)

[[1 2 3]
 [4 5 6]]
array2 type :  <class 'numpy.ndarray'>
array2 shape :  (2, 3)

[[1 2 3]]
array3 type :  <class 'numpy.ndarray'>
array3 shape :  (1, 3)


In [4]:
# 차원 출력
print("array1 dim : ", a1.ndim)
print("array2 dim : ", a2.ndim)
print("array3 dim : ", a3.ndim)

array1 dim :  1
array2 dim :  2
array3 dim :  2


- `np.arange(x)` 함수를 사용하여 `0`부터 `(x-1)`까지의 값을 순차적 배열의 데이터 값으로 생성할 수 있다.

In [5]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [6]:
a = np.arange(1, 20, 3)    # 1 <= x < 20, 간격 : 3
print(a)

[ 1  4  7 10 13 16 19]


## <a id='toc1_2_'></a>[(2) Numpy 배열 초기화](#toc0_)

In [7]:
zero_a = np.zeros((2, 5))    # 0으로 채워진 2x5 형태의 배열 생성
one_a = np.ones((3, 4))    # 1로 채워진 3x4 형태의 배열 생성

print(zero_a)
print(one_a)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [8]:
zero_b = np.zeros_like(one_a)    # 이미 생성된 배열의 구조(3x4)와 동일한 구조를 유지한 상태에서 0으로 초기화

print(zero_b)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
one_b = np.ones_like(zero_a)    # 이미 생성된 배열의 구조(3x4)와 동일한 구조를 유지한 상태에서 1로 초기화

print(one_b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [10]:
full_a = np.full((4, 3), 9)    # 모든 값이 9인 4x3 형태의 배열 생성
random_a = np.random.random((3, 4))    # 모든 값이 랜덤값인 3x4 형태의 배열 생성

print(full_a)
print(random_a)

[[9 9 9]
 [9 9 9]
 [9 9 9]
 [9 9 9]]
[[0.00680251 0.64246597 0.69947296 0.62301808]
 [0.75618663 0.63781803 0.72913366 0.34346381]
 [0.23088761 0.84584517 0.61568945 0.64637078]]


In [11]:
eye_a = np.eye(4)    # 주대각선이 1인 대각행렬 형태의 4x4 배열 생성

print(eye_a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## <a id='toc1_3_'></a>[(3) NumPy 배열 크기 변형](#toc0_)

- `reshape` 함수의 옵션으로 `order='F'`를 선언하면 값을 <ins>열</ins>부터 채워 넣는다.
    - `order` 옵션을 사용하지 않거나 값을 `order='T'`로 선언하면 값을 <ins>행</ins>부터 채워 넣는다.
- `reshape` 함수는 지정된 크기로 변경이 불가능하면 오류가 발생한다.
    - 예) `(10, )` 배열을 `(4, 3)` 배열로 변경할 경우

In [12]:
array1 = np.arange(12)    # 1차원 형태의 배열 생성
print("array1 : \n", array1)

array2 = array1.reshape(3, 4)    # 3x4 형태로 배열 크기 변경 (값을 행부터 채워넣기(T, 생략 가능))
print("array2 : \n", array2)

array3 = array1.reshape(3, 4, order='F')    # 값을 열부터 채워넣기(F)
print("array3 : \n", array3)

array1 : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
array2 : 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
array3 : 
 [[ 0  3  6  9]
 [ 1  4  7 10]
 [ 2  5  8 11]]


- `reshape`을 사용할 때 인자로 `-1`을 입력하는 경우가 일반적인데, `-1`을 인자로 사용하면 원래 배열과 호환되는 크기로 자동으로 변환해준다.

In [13]:
array1 = np.arange(10)
array2 = array1.reshape(-1, 5)    # 원래 배열과 호환되는 크기로 자동으로 변환 (행: -1, 컬럼: 5)

print(array2)
print("array2 dim : ", array2.ndim)
print("array2 shape : ", array2.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]]
array2 dim :  2
array2 shape :  (2, 5)


- `reshape`을 활용하면 다음과 같이 **다차원 배열**로도 변환이 가능하다.

In [15]:
array1 = np.arange(12)
array2 = array1.reshape(2, 3, 2, order='F')    # 2차원 3x2 형태의 배열로 변환

print(array2)
print("array2 dim : ", array2.ndim)
print("array2 shape : ", array2.shape)

[[[ 0  6]
  [ 2  8]
  [ 4 10]]

 [[ 1  7]
  [ 3  9]
  [ 5 11]]]
array2 dim :  3
array2 shape :  (2, 3, 2)


- 현재까지 구성한 다차원 배열을 **1차원 배열**로 만들 수 있다.

In [16]:
array3 = array2.flatten()    # 다차원 배열을 1차원 배열로 만들기

print(array3)

[ 0  6  2  8  4 10  1  7  3  9  5 11]


## <a id='toc1_4_'></a>[(4) NumPy 배열 데이터 추출하기](#toc0_)

### <a id='toc1_4_1_'></a>[인덱싱(Indexing)](#toc0_)

In [17]:
array1 = np.arange(1, 10)
print("array1 : ", array1)

value1 = array1[2]
value2 = array1[-2]    # 뒤에서 두 번째 요소 가져오기

print(value1)
print(value2)

array1 :  [1 2 3 4 5 6 7 8 9]
3
8


In [20]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)    # 3x3 배열로 변환
print("array2 : \n", array2)

value1 = array2[0, 0]
value2 = array2[-1, -1]
value3 = array2[-1, -2]

print(value1)
print(value2)
print(value3)

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
1
9
8


### <a id='toc1_4_2_'></a>[슬라이싱(Slicing)](#toc0_)

In [21]:
array1 = np.arange(1, 10)
array2 = array1[0:3]
array3 = array1[:3]    # 시작 인덱스를 0으로 간주한다.
array4 = array1[3:]    # 종료 인덱스를 맨 마지막 인덱스로 간주한다.

print(type(array2))
print(array2)
print(array3)
print(array4)

<class 'numpy.ndarray'>
[1 2 3]
[1 2 3]
[4 5 6 7 8 9]


- **2차원 배열**에서의 슬라이싱도 1차원 배열에서의 슬라이싱과 유사하며, 콤마(,)로 행과 컬럼 인덱스를 지칭하는 부분만 다르다.

In [23]:
array1 = np.arange(1, 10)
array2 = array1.reshape(3, 3)
print("array2 : \n", array2)

print("array2[0:2, 0:2]\n", array2[0:2, 0:2], "\n")
print("array2[1:3, 0:3]\n", array2[1:3, 0:3], "\n")
print("array2[:2, 1:]\n", array2[:2, 1:], "\n")
print("array2[:2, 0]\n", array2[:2, 0], "\n")

array2 : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2[0:2, 0:2]
 [[1 2]
 [4 5]] 

array2[1:3, 0:3]
 [[4 5 6]
 [7 8 9]] 

array2[:2, 1:]
 [[2 3]
 [5 6]] 

array2[:2, 0]
 [1 4] 



## <a id='toc1_5_'></a>[(5) NumPy 선형 대수 기본 연산](#toc0_)

### <a id='toc1_5_1_'></a>[행렬 내적(행렬 곱)](#toc0_)

- 행렬 내적은 행렬 곱을 의미한다.
- 두 행렬 A와 B의 내적은 `np.dot` 함수를 이용해서 쉽게 계산이 가능하다.

![행렬 내적(행렬 곱)의 예](https://thebook.io/img/007019/081.jpg)

In [24]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
array2 = np.array([[7, 8],
                   [9, 10],
                   [11, 12]])

dot_array = np.dot(array1, array2)   # 행렬 내적(행렬 곱)
print(dot_array)

[[ 58  64]
 [139 154]]


### <a id='toc1_5_2_'></a>[전치 행렬](#toc0_)

In [25]:
array1 = np.array([[1, 2, 3],
                   [4, 5, 6]])
transpose_array = np.transpose(array1)

print(transpose_array)

[[1 4]
 [2 5]
 [3 6]]


## <a id='toc1_6_'></a>[(6) NumPy 기술 통계](#toc0_)

In [31]:
x = np.array([18, 5, 19, 23, 19, -8, 10, 0, 0, 5, 2, 15, 8, 2, 1, 3, -4])

### <a id='toc1_6_1_'></a>[배열 데이터 개수](#toc0_)

In [32]:
print(len(x))    # 배열 데이터 개수

17


### <a id='toc1_6_2_'></a>[평균, 분산, 표준편차](#toc0_)

In [28]:
print(np.mean(x))   # 평균
print(np.var(x))   # 분산
print(np.std(x))   # 표준편차

6.9411764705882355
76.0553633217993
8.720972613292586


### <a id='toc1_6_3_'></a>[최댓값, 최솟값, 중앙값](#toc0_)

In [29]:
print(np.max(x))    # 최댓값
print(np.min(x))    # 최솟값
print(np.median(x))    # 중앙값

23
-8
5.0


### <a id='toc1_6_4_'></a>[사분위수](#toc0_)

In [30]:
print(np.percentile(x, 25))    # 1사분위수
print(np.percentile(x, 50))    # 2사분위수
print(np.percentile(x, 75))    # 3사분위수

1.0
5.0
15.0
