# 20240621 (시험 D-1)
---

## 제1유형
---

### 문제 1 (21-2)

In [7]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210201.csv')

# crim 항목의 상위에서 10번째 값(상위 10개의 값 중에서 가장 작은 값) 구하기
top10s = df.sort_values(by='crim', ascending=False).head(10)
top10 = top10s['crim'].iloc[9]

# 상위 10개의 값 변환하기
df['crim'] = np.where(df['crim'] >= top10, top10, df['crim'])

# age가 80이상인 값에 대하여 crim의 평균 구하기
result = df['crim'][df['age'] >= 80].mean()
answer = round(result, 2)
print(answer)

5.76


### 문제 2 (21-2)

In [12]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210202.csv')

# 첫 번째 행부터 순서대로 80%까지의 데이터를 훈련 데이터로 추출하기
nrow = int(len(df) * 0.8)
df = df[:nrow]

# total_bedrooms 변수의 NA을 total_bedrooms 변수의 중앙값으로 대체하기
a = df['total_bedrooms'].std()

df['total_bedrooms'] = df['total_bedrooms'].fillna(df['total_bedrooms'].median())

b = df['total_bedrooms'].std()

# 대체 전의 total_bedrooms 변수 표준편차 값과 대체 후의 total_bedrooms 변수 표준편차 값의 차이 구하기
answer = round(np.abs(a - b), 2)
print(answer)

1.98


### 문제 3 (21-2)

In [15]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210203.csv')

# charges 항목에서 이상값의 합 구하기
target = df['charges']

mean_value = target.mean()
std_value = target.std()

lower = mean_value - 1.5 * std_value
upper = mean_value + 1.5 * std_value

cond = (target <= lower) | (upper <= target)
result = df['charges'][cond].sum()

answer = int(result)
print(answer)

6421430


### 문제 4 (21-3)

In [16]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210301.csv')

# 결측값이 있는 행 제거하기
df = df.dropna()

# 데이터의 순서대로 상위 70%의 데이터를 학습 데이터로 만들기
nrow = int(len(df) * 0.7)
train_df = df[:nrow]

# 훈련 데이터의 housing_median_age 컬럼의 제1사분위수(Q1) 구하기
q1 = train_df['housing_median_age'].quantile(0.25)
answer = int(q1)

print(answer)

19


### 문제 5 (21-3)

In [39]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210302.csv')

# 데이터가 없는 것을 결측값으로 하여 결측값의 비율 구하기
total_value_counts = len(df)
na_value_counts = df.isna().sum()

na_ratio = na_value_counts / total_value_counts

# 결측값의 비율이 가장 높은 컬럼 이름 구하기
na_ratio = pd.DataFrame(na_ratio)

sorted_na_ratio = na_ratio.sort_values(by=0, ascending=False)    # 내림차순 정렬
print(sorted_na_ratio.index[0])


Age


### 문제 6 (21-3)

In [53]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P210303.csv')

# country, year, new_sp 컬럼에 결측값이 있을 경우 제거하기
df['country'] = df['country'].dropna()
df['year'] = df['year'].dropna()
df['new_sp'] = df['new_sp'].dropna()

# 2000년도에 국가별 결핵 발생 건수에 대한 평균 결핵 발생 건수 구하기 (소수점 둘째 자리)
cond = df['year'] == 2000
target_df = df[cond]

mean_value = target_df['new_sp'].mean()
answer1 = round(mean_value, 2)
print(answer1)

# 2000년도의 결핵 발생 건수가 2000년도 국가별 결핵 발생 건수에 대한 평균 결핵 발생 건수보다 결핵 발생 건수가 높은 국가의 개수 구하기
cond = target_df['new_sp'] >= mean_value
result = len(target_df['country'][cond])
print(result)

7865.34
38


### 문제 7 (22-4)

In [55]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220401.csv')

# y변수의 1사분위와 3사분위 값 구하기
q1 = df['y'].quantile(0.25)
q3 = df['y'].quantile(0.75)
print(q1, q3)

# (2) 3사분위수에서 1사분위수를 뺀 값(iqr) 구하기
iqr = q3 - q1
print(iqr)

# (3) 소수점 이하는 버리고 정수로 출력하기
answer = int(iqr)
print(answer)

40.25 77.0
36.75
36


### 문제 8 (22-4)

In [65]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220402.csv')

# 좋아요 수와 놀랐어요를 긍정의 평가로 보고 전체 반응에서 긍정인 비율 구하기
df['postive_ratio'] = (df['num_loves'] + df['num_wows']) / df['num_reactions']

# 긍정인 비율이 0.4보다 크고 0.5보다 작은 비디오 개수 구하기
cond = (df['status_type'] == 'video') & ((df['postive_ratio'] > 0.4) & (df['postive_ratio'] < 0.5))
result = df[cond]

answer = len(result)
print(answer)

90


### 문제 9 (22-4)

In [69]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220403.csv')

# date_added 컬럼을 datetime64로 바꾸기
df['date_added'] = pd.to_datetime(df['date_added'])

# 2018년 1월에 넷플릭스에서 추가한 작품 중, United Kingdom에서 단독으로 제작된 작품 개수 구하기
cond1 = (df['date_added'].dt.year == 2018) & (df['date_added'].dt.month == 1)
cond2 = df['country'] == 'United Kingdom'
result = df[cond1 & cond2]

answer = len(result)
print(answer)

6


### 문제 10 (22-5)

In [78]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220501.csv', encoding='euckr')

# 기준에 따른 데이터 추출하기
cond1 = df['종량제봉투종류'] == '규격봉투'
cond2 = df['종량제봉투용도'] == '음식물쓰레기'
cond3 = df['2L가격'] != 0

df = df[cond1 & cond2 & cond3]

# 평균 가격 구하기
result = df['2L가격'].mean()
answer = int(result)
print(answer)

120


### 문제 11 (22-5)

In [79]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220502.csv')

# BMI 구하기
df['BMI'] = df['Weight'] / ((df['Height'] / 100) ** 2)

# 정상 체중 범위 구간, 위험 체중 범위 구간 인원 구하기
target = df['BMI']
cond1 = (18.5 <= target) & (target < 23)
cond2 = (23 <= target) & (target < 25)

healthy = len(target[cond1])
danger = len(target[cond2])

# 각 인원의 차이를 절댓값으로 나타내기
answer = int(np.abs(healthy - danger))
print(answer)

28


### 문제 12 (22-5)

In [93]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P220503.csv', encoding='euckr')

# 순전입학생수가 가장 큰 학교의 전체 학생수 구하기
df['순전입학생수'] = df['전입학생수(계)'] - df['전출학생수(계)']

df = df.sort_values(by='순전입학생수', ascending=False)
# print(df[['학교명', '전체학생수(계)', '순전입학생수']])

answer = df['전체학생수(계)'].iloc[0]
print(answer)

956


### 문제 13 (23-6)

In [119]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P230601.csv')

# 날짜를 datetime64로 바꾸기
df['신고일시'] = pd.to_datetime(df['신고일시'])
df['출동일시'] = pd.to_datetime(df['출동일시'])

# 출동소방서별 신고일시로부터 출동일시까지의 연도별 월평균 구하기
df['출동시간(초)'] = (df['출동일시'] - df['신고일시']).dt.total_seconds()

new_df = df.groupby([df['출동소방서'], df['신고일시'].dt.year, df['신고일시'].dt.month]).mean('출동시간(초)')

# 가장 늦게 출동한 출동 소방서의 월평균 시간을 분단위로 나타내기
new_df = new_df.sort_values(by='출동시간(초)', ascending=False)
answer = int(new_df.iloc[0] / 60)    # 분단위
print(answer)

64


C:\Users\kss34\AppData\Local\Temp\ipykernel_16588\2583677886.py:17: FutureWarning: Calling int on a single element Series is deprecated and will raise a TypeError in the future. Use int(ser.iloc[0]) instead
  answer = int(new_df.iloc[0] / 60)    # 분단위


### 문제 14 (23-6)

In [125]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P230602.csv')

# 교사 1인당 학생 수가 가장 많은 학교 선정하기
df['student_number_per_teacher'] = (df['student_1'] + df['student_2'] + df['student_3'] + df['student_4'] + df['student_5'] + df['student_6']) / df['teacher']

df = df.sort_values(by='student_number_per_teacher', ascending=False)
result = df['school_name'].iloc[0]

# 선정된 학교의 교사수 나타내기
cond = df['school_name'] == result
answer = df['teacher'][cond].iloc[0]
print(answer)

6


### 문제 15 (23-6)

In [148]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P230603.csv')

# 년월 항목을 datetime64로 바꾸기
df['년월'] = pd.to_datetime(df['년월'])

# 연도별 월평균 범죄 건수 구하기
df['총범죄건수'] = df['강력범'] + df['절도범'] + df['폭력범'] + df['지능범'] + df['풍속범'] + df['기타형사범']

new_df = df.groupby([df['년월'].dt.year]).mean('총범죄건수')   # 연도별로 그룹화할 경우, 월평균 값을 구할 수 있다.

# 가장 범죄가 많이 발생한 연도의 월평균 범죄 건수 구하기
sorted_new_df = new_df.sort_values(by='총범죄건수', ascending=False)
answer = int(sorted_new_df['총범죄건수'].iloc[0])

print(answer)


19329


### 문제 16 (23-7)

In [171]:
import numpy as np
import pandas as pd
from scipy.stats import zscore

df = pd.read_csv('./datasets/P230701.csv')

# 국어, 수학, 영어, 과학 과목 중 가장 많은 학생들이 응시한 시험 선택하기
count_kor = df['국어'].dropna().count()
count_math = df['수학'].dropna().count()
count_eng = df['영어'].dropna().count()
count_sci = df['과학'].dropna().count()

print(count_kor, count_math, count_eng, count_sci)

# 해당 과목의 점수를 표준화 했을 때, 가장 큰 표준화 점수 구하기
target = df['국어']

target = target.dropna()   # 결측치 제거

z = zscore(target)
answer = z.max()
print(answer)

13 12 11 9
1.713855688712825


### 문제 17 (23-7)

In [186]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P230702.csv')

# 32개 변수간 상관 계수 확인하기
df_corr = df.corr()

# var_11 컬럼과 상관 계수의 절댓값이 가장 큰 변수 찾기
var11_corr = df_corr['var_11']
result = np.abs(result)

sorted_result = result.sort_values(ascending=False).index[1]  # 변수명 찾기

# 해당 변수의 평균값 구하기
answer = df[sorted_result].mean()
print(answer)

0.06404313251242914


### 문제 18 (23-7)

In [188]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/P230703.csv')

# var_6 컬럼의 1, 3사분위수 각각 IQR의 1.5배 벗어난 이상치의 숫자 구하기
target = df['var_6']

q1 = target.quantile(0.25)
q3 = target.quantile(0.75)
iqr = q3 - q1

lower = q1 - 1.5 * iqr
upper = q3 + 1.5 * iqr

cond = (target < lower) | (upper < target)   # 통계적으로 경계선 안에 있는 값은 포함하지 않는다.
result = df[cond]

answer = len(result)
print(answer)

8


### 문제 19 (시험장 예제)

In [189]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

df = pd.read_csv('./datasets/mtcars.csv')

mms = MinMaxScaler()
df['qsec'] = mms.fit_transform(df[['qsec']])     # df 안의 컬럼명을 대괄호로 둘러싼다. (2차원으로 만들기)

cond = df['qsec'] > 0.5
result = df[cond]

answer = int(len(result))
print(answer)

9


### 문제 20 (연습)

In [191]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/M1-1.csv')

# 순서대로 70%의 데이터를 훈련 데이터로 만들기
nrow = int(len(df) * 0.7)
train_df = df[:nrow]

# price 기준으로 상위 5개 데이터에 대하여 깊이 비율(depth)의 중앙값을 정수로 출력하기
result = train_df.sort_values(by='price', ascending=False).head(5)
median_value = result['depth'].median()

answer = int(median_value)
print(answer)


62


### 문제 21 (연습)

In [203]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/M1-2.csv')

target = df['TotalCharges']

# TotalCharges 항목에서 결측값 제거
target = pd.to_numeric(target, errors='coerce')   # 공백, NaN을 포함한 모든 결측치들을 NaN으로 만들기
target = target.dropna()   # NaN 제거하기

# 형 변환 (object -> float)
target = target.astype('float')

# TotalCharges 항목에서 이상값 제거
mean_value = target.mean()
std_value = target.std()

lower = mean_value - 1.5 * std_value
upper = mean_value + 1.5 * std_value

cond = (lower <= target) & (target <= upper)
result = target[cond]

# 평균을 정수로 출력하기
answer = int(result.mean())
print(answer)

1663


### 문제 22 (연습)

In [210]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/mtcars.csv')

# 수동(am=1) 중에서 가장 마력(hp)이 작은 5개의 데이터의 평균 연비(mpg) 구하기
cond1 = df['am'] == 1
target1 = df[cond1].sort_values(by='hp', ascending=True).head(5)
manual_mean_mpg = target1['mpg'].mean()

# 자동(am=0) 중에서 가장 마력(hp)이 작은 5개의 데이터의 평균 연비(mpg) 구하기
cond2 = df['am'] == 0
target2 = df[cond2].sort_values(by='hp', ascending=True).head(5)
auto_mean_mpg = target2['mpg'].mean()

# 두 값의 차이 구하기
answer = round(np.abs(manual_mean_mpg - auto_mean_mpg), 1)
print(answer)

8.4


### 문제 23 (연습)

In [212]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/M2-1.csv')

# 데이터의 순서대로 70%의 데이터를 훈련 데이터로 추출하기
nrow = int(len(df) * 0.7)
train_df = df[:nrow]

# Ozone 항목의 결측값을 평균으로 변경하기
a = round(train_df['Ozone'].median(), 1)

train_df['Ozone'] = train_df['Ozone'].fillna(train_df['Ozone'].mean())

b = round(train_df['Ozone'].median(), 1)

# 변경 전, 후의 중앙값 차이 구하기
answer = round(np.abs(a - b), 1)
print(answer)

7.7


C:\Users\kss34\AppData\Local\Temp\ipykernel_16588\914386028.py:13: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  train_df['Ozone'] = train_df['Ozone'].fillna(train_df['Ozone'].mean())


### 문제 24 (연습)

In [216]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/M2-2.csv')

# HAIR가 White Hair이고 EYE가 Blue Eyes인 데이터를 훈련 데이터로 추출하기
cond1 = df['HAIR'] == 'White Hair'
cond2 = df['EYE'] == 'Blue Eyes'
train_df = df[cond1 & cond2]

# APPEARANCES에서 이상값을 제외한 평균 구하기 (이상값 : 평균 1.5배 표준편차)
target = train_df['APPEARANCES']

mean_value = round(target.mean(), 2)
std_value = round(target.std(), 2)

lower = mean_value - 1.5 * std_value
upper = mean_value + 1.5 * std_value

cond = (lower <= target) & (target <= upper)    # 이상값을 제외한 값을 구할 때는 경계선 값을 포함한다.
result = target[cond].mean()

answer = round(result, 2)
print(answer)

30.15


### 문제 25 (연습)

In [217]:
import numpy as np
import pandas as pd

df = pd.read_csv('./datasets/M2-3.csv')

# 매출(Sales)의 이상값을 제외한 데이터를 훈련 데이터로 선정하기
target = df['Sales']

mean_value = target.mean()
std_value = target.std()

lower = mean_value - 1.5 * std_value
upper = mean_value + 1.5 * std_value

cond = (lower <= target) & (target <= upper)
train_data = df[cond]

# Age의 표준편차 구하기
result = train_data['Age'].std()
answer = round(result, 2)

print(answer)

16.05


## 제2유형
---

### 문제 1 (21-2)

In [227]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from sklearn.model_selection import *

df1 = pd.read_csv('./datasets/P210204-01.csv')
df2 = pd.read_csv('./datasets/P210204-02.csv')

# 데이터 형 변환 (범주형)
df1['Reached.on.Time_Y.N'] = df1['Reached.on.Time_Y.N'].astype('category')

# 독립 변수, 종속 변수 분리
x = df1.drop('Reached.on.Time_Y.N', axis=1)   # 독립 변수
y = df1['Reached.on.Time_Y.N']   # 종속 변수

# 원-핫 인코딩
x_encoded = pd.get_dummies(x).drop('ID', axis=1)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
cm = confusion_matrix(y_valid, pred, labels=[1, 0])
print(cm)

print(accuracy_score(y_valid, pred))
print(precision_score(y_valid, pred))
print(recall_score(y_valid, pred))
print(f1_score(y_valid, pred))
print(roc_auc_score(y_valid, pred))

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test).drop('ID', axis=1)    # 원-핫 인코딩

pred = md.predict_proba(x_test_encoded)    # 예측
print(pred)


# CSV 내보내기
result = pd.DataFrame({
    'ID': df2['ID'],
    'pred': pred[:, 1]
})
print(result)

result.to_csv('./outputs/20240621_Q1.csv', index=False)

[1 1 0 ... 0 0 0]
[[925 387]
 [235 456]]
0.6894658012980529
0.7974137931034483
0.7050304878048781
0.7483818770226537
0.6824718285623522
[[0.44333333 0.55666667]
 [0.26333333 0.73666667]
 [0.61       0.39      ]
 ...
 [0.46666667 0.53333333]
 [0.36333333 0.63666667]
 [0.27       0.73      ]]
         ID      pred
0      8010  0.556667
1      8011  0.736667
2      8012  0.390000
3      8013  0.603333
4      8014  0.613333
...     ...       ...
2985  10995  0.626667
2986  10996  0.540000
2987  10997  0.533333
2988  10998  0.636667
2989  10999  0.730000

[2990 rows x 2 columns]


### 문제 2 (21-3)

In [236]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *

df1 = pd.read_csv('./datasets/P210304-01.csv')
df2 = pd.read_csv('./datasets/P210304-02.csv')

# 데이터 형 변환 (수치형 -> 범주형)
df1['TravelInsurance'] = df1['TravelInsurance'].astype('category')

# 독립 변수, 종속 변수 분리
x = df1.drop('TravelInsurance', axis=1)
y = df1['TravelInsurance']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x).drop('X', axis=1)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
cm = confusion_matrix(y_valid, pred, labels=[1, 0])
print(cm)

print(accuracy_score(y_valid, pred))
print(recall_score(y_valid, pred))
print(precision_score(y_valid, pred))
print(f1_score(y_valid, pred))
print(roc_auc_score(y_valid, pred))

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test).drop('X', axis=1)    # 원-핫 인코딩

pred = md.predict_proba(x_test_encoded)   # 예측
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'index': df2['X'],
    'y_pred': pred[:, 1]
})
print(result)

result.to_csv('./outputs/20240621_Q2.csv', index=False)

[1 0 0 0 1 0 0 0 0 1 0 0 0 1 1 0 1 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 1 0 0 0 0 0 1 1 1 0 1 1 0 1 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0
 1 1 0 1 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 0 0 0 1 0 1 1 1 1 0
 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 1 0 1 0 0 0 1 0 0 0
 0 0 1 1 1 0 0 1 1 1 1 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1
 0 1 1 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 0
 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 1 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 1 0 1
 0 1 1 1 0 0 1 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0 0 0 0
 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 1 1 1 0 1 0 1 1 1 1 0 0
 1 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0
 1 0 0]
[[ 77  65]
 [ 31 200]]
0.7426273458445041
0.5422535211267606
0.7129629629629629
0.616
0.7040271934638132
[[0.11       0.89      ]
 [0.19531746 0.80468254]
 [0.701      0.299     ]
 [0.87166667 0.12833333]
 [0.95705556 0.04294444]
 [0.66990873

### 문제 3 (22-4)

In [251]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.preprocessing import *

df1 = pd.read_csv('./datasets/P220404-01.csv')
df2 = pd.read_csv('./datasets/P220404-02.csv')

# 데이터 형 변환 (object -> category)
df1['Segmentation'] = df1['Segmentation'].astype('category')

# 독립 변수, 종속 변수 분리
x = df1.drop('Segmentation', axis=1)
y = df1['Segmentation']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x).drop('ID', axis=1)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 평가
cm = confusion_matrix(y_valid, pred, labels=['A', 'B', 'C', 'D'])
print(cm)

print(f1_score(y_valid, pred, average='macro'))


# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test).drop('ID', axis=1)   # 원-핫 인코딩

pred = md.predict(x_test_encoded)   # 예측
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'ID': df2['ID'],
    'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q3.csv', index=False)

['D' 'C' 'A' ... 'C' 'B' 'C']
[[159 102  76  72]
 [ 99 135 113  49]
 [ 55 106 208  51]
 [101  32  25 284]]
0.46579106638848067
['B' 'C' 'C' ... 'B' 'B' 'D']
          ID pred
0     458989    B
1     458994    C
2     459000    C
3     459003    C
4     459005    A
...      ...  ...
2149  467950    A
2150  467954    D
2151  467958    B
2152  467961    B
2153  467968    D

[2154 rows x 2 columns]


### 문제 4 (22-5)

In [258]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.preprocessing import *
from sklearn.metrics import *
from sklearn.model_selection import *

df1 = pd.read_csv('./datasets/P220504-01.csv')
df2 = pd.read_csv('./datasets/P220504-02.csv')

# 독립 변수, 종속 변수 설정
x = df1.drop('price', axis=1)
y = df1['price']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestRegressor(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
result = mean_squared_error(y_valid, pred, squared=False)   # RMSE
print(result)

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test)   # 원-핫 인코딩

# 공통 피쳐 추출
common_features = list(set(x_encoded.columns).intersection(x_test_encoded.columns))
x_train_common = x_encoded[common_features]
x_test_common = x_test_encoded[common_features]

# 모델링
md = RandomForestRegressor(n_estimators=300)
md.fit(x_train_common, y)

# 예측
pred = md.predict(x_test_common)
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q4.csv', index=False)

[30630.87       14885.85666667 18691.69       ... 16395.11638889
 23833.65       18607.75333333]
2841.633949298214


c:\Users\kss34\anaconda3\envs\bigdata\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


[17989.73       29564.03333333 24319.5        ... 16988.35
 10805.16333333 16599.03666667]
              pred
0     17989.730000
1     29564.033333
2     24319.500000
3     23295.200000
4     20327.300000
...            ...
3877  18963.876667
3878  15790.273333
3879  16988.350000
3880  10805.163333
3881  16599.036667

[3882 rows x 1 columns]


### 문제 5 (23-6)

In [279]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.preprocessing import *
from sklearn.model_selection import *
from sklearn.metrics import *

df1 = pd.read_csv('./datasets/P230604-01.csv')
df2 = pd.read_csv('./datasets/P230604-02.csv')

# 데이터 형변환 (범주형)
df1['price_range'] = df1['price_range'].astype('category')

# 기타 독립 변수들 (수치형 -> 범주형)
df1['blue'] = df1['blue'].astype('category')
df1['dual_sim'] = df1['dual_sim'].astype('category')
df1['four_g'] = df1['four_g'].astype('category')
df1['n_cores'] = df1['n_cores'].astype('category')
df1['three_g'] = df1['three_g'].astype('category')
df1['touch_screen'] = df1['touch_screen'].astype('category')
df1['wifi'] = df1['wifi'].astype('category')

df2['blue'] = df2['blue'].astype('category')
df2['dual_sim'] = df2['dual_sim'].astype('category')
df2['four_g'] = df2['four_g'].astype('category')
df2['n_cores'] = df2['n_cores'].astype('category')
df2['three_g'] = df2['three_g'].astype('category')
df2['touch_screen'] = df2['touch_screen'].astype('category')
df2['wifi'] = df2['wifi'].astype('category')

# 독립 변수, 종속 변수 분리
x = df1.drop('price_range', axis=1)
y = df1['price_range']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
cm = confusion_matrix(y_valid, pred, labels=[3, 2, 1, 0])
print(cm)

print(f1_score(y_valid, pred, average='macro'))

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test.drop('id', axis=1))   # 원-핫 인코딩

pred = md.predict(x_test_encoded)   # 예측
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q5.csv', index=False)

[2 3 3 2 3 2 1 3 2 0 1 3 0 3 3 2 0 2 2 3 2 0 3 0 3 1 1 0 0 0 1 1 3 0 0 3 1
 0 1 3 3 3 2 0 0 3 2 0 2 2 3 0 1 1 0 2 1 0 2 0 3 0 1 0 3 2 1 1 1 2 3 3 1 3
 2 3 2 1 1 1 0 1 3 2 0 1 3 2 1 0 1 3 1 2 1 0 2 3 0 1 3 1 1 1 3 3 1 1 2 3 0
 2 2 3 0 3 0 3 0 0 3 1 3 0 0 0 2 0 1 3 1 2 0 1 3 0 2 0 3 0 0 3 1 1 3 0 0 0
 2 1 0 3 2 1 1 3 3 1 2 3 0 2 3 0 2 1 2 3 1 3 0 3 2 0 3 1 2 2 0 2 3 0 0 1 0
 2 0 3 1 0 3 2 0 3 1 3 3 0 1 2 0 0 3 3 2 1 0 0 3 0 1 3 2 2 3 3 0 0 0 1 2 0
 2 1 2 1 1 3 1 1 0 3 0 1 1 1 3 2 0 3 3 2 2 2 0 2 3 1 0 0 2 0 0 2 3 0 0 2 2
 1 3 1 0 1 2 3 1 1 3 1 3 2 3 3 2 3 0 2 3 0 3 2 0 0 3 0 0 0 3 0 2 1 3 1 3 1
 2 1 3 2 2 1 0 2 0 2 3 1 3 1 3 1 2 3 1 1 3 0 3 1 2 0 2 1 2 3 2 2 2 1 2 2 1
 0 3 2 2 2 1 2 1 2 1 1 0 0 1 0 0 0 3 2 3 3 3 1 2 1 2 3 3 1 0 1 1 1 0 0 3 1
 0 2 2 1 3 0 1 2 1 0 2 1 0 2 3 2 0 0 0 2 3 0 1 2 2 3 1 3 1 1 2 1 3 2 3 1 1
 1 1 2 3 0 0 3 2 2 2 0 2 0 3 1 1 1 0 0 3 2 0 0 0 3 3 1 1 0 1 2 3 1 3 1 3 0
 1 0 3 1 3 3 3 0 1 1 0 1 3 1 1 1 0 2 2 0 0 1 1 0 1 3 3 2 0 2 0 3 3 0 2 0 2
 3 1 2 0 2 3 0 2 1 0 0 1 

### 문제 6 (23-7)

In [289]:
import pandas as pd
from sklearn.preprocessing import *
from sklearn.ensemble import *
from sklearn.metrics import *
from sklearn.model_selection import *

df1 = pd.read_csv('./datasets/P230704-01.csv')
df2 = pd.read_csv('./datasets/P230704-02.csv')

# 라벨 인코딩
le = LabelEncoder()
le.fit(df1['업종명'])

df1['업종명'] = le.transform(df1['업종명'])
df2['업종명'] = le.transform(df2['업종명'])

# 독립 변수, 종속 변수 분리
x = df1.drop('이용금액', axis=1)
y = df1['이용금액']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x.drop('ID', axis=1))

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
result = mean_squared_error(y_valid, pred, squared=False)   # RMSE
print(result)

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x)   # 원-핫 인코딩

# 공통 피쳐 추출
common_features = list(set(x_encoded.columns).intersection(x_test_encoded.columns))
x_train_common = x_encoded[common_features]
x_test_common = x_test_encoded[common_features]

# 모델링
md = RandomForestRegressor(n_estimators=300)
md.fit(x_train_common, y)

# 예측
pred = md.predict(x_test_common)
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q6.csv', index=False)

[   47933820  9188508100    68969330     9195480   183949093    64637690
   450628146     2004800   473471719     3082840  1243513464   358497400
   341276414  5706601337   553327076   259699490   736787276    83959994
   102120653   205726744   357214269  1666656825   786460793   942508514
   993332454   538430047    90078400   727870651   478122862      781180
    71049200    14647173  1999305771   453355296    64637690    19978450
    48120320   335943732   998993627   974460147  3673219409  5045240227
  3750804082   897381317  1268967870  1641863482   149044763   205467990
     2144770  5045240227  5577092664     4477800     9574379  5269157126
  1608778370      389900   469249380  1111657582    35197620   641964522
   213749640      407000  3036993427  1086914020  1014343385   161803565
   550051686   491015045   158093435    84607490     6949242   237842923
  3288151742   166933698   390990650    72264355  4762451543    84410623
     1590580  3304517211     3329700     3337200   

c:\Users\kss34\anaconda3\envs\bigdata\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


[3.07980990e+09 3.02361408e+08 1.21633915e+08 ... 1.01163771e+08
 2.01131551e+08 5.76319102e+07]
              pred
0     3.079810e+09
1     3.023614e+08
2     1.216339e+08
3     4.451371e+08
4     4.370012e+08
...            ...
2240  2.913167e+07
2241  1.221607e+08
2242  1.011638e+08
2243  2.011316e+08
2244  5.763191e+07

[2245 rows x 1 columns]


### 문제 7 (환경 체험 예제)

In [ ]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.metrics import *
from sklearn.model_selection import *
from sklearn.preprocessing import *

train = pd.read_csv("./datasets/customer_train.csv")   # df1
test = pd.read_csv("./datasets/customer_test.csv")   # df2

# 결측치 대치 (중앙값으로 으로 대치)
train['환불금액'] = train['환불금액'].fillna(train['환불금액'].mean())
test['환불금액'] = test['환불금액'].fillna(test['환불금액'].mean())

# 자료형 변환 (범주형)
train['성별'] = train['성별'].astype('category')

# 라벨 인코딩 (Object -> 수치형)
columns_to_encode = ['주구매상품', '주구매지점']

for column in columns_to_encode:
	le = LabelEncoder()
	# 테스트 세트에 없는 레이블을 처리하기 위해 각 열에 대해 학습 데이터와 테스트 데이터를 연결한 후 LabelEncoder를 학습시킨다.
	combined_data = pd.concat([train[column], test[column]], axis=0)
	le.fit(combined_data)
	
	train[column] = le.transform(train[column])
	test[column] = le.transform(test[column])

# 독립변수, 종속 변수 분리
x = train.drop('성별', axis=1)
y = train['성별']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x.drop('회원ID', axis=1))

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 예측
pred = md.predict(x_valid)
print(pred)

# 모델 평가
cm = confusion_matrix(y_valid, pred, labels=[1, 0])
print(cm)

print(roc_auc_score(y_valid, pred))

# 테스트 데이터 평가
x_test = test

x_test_encoded = pd.get_dummies(x_test.drop('회원ID', axis=1))   # 원-핫 인코딩

pred = md.predict(x_test_encoded)
print(pred)

# CSV 내보내기
result = pd.DataFrame({
	'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q7.csv', index=False)

### 문제 8 (연습)

In [304]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.preprocessing import *

df1 = pd.read_csv('./datasets/M1-4-1.csv')
df2 = pd.read_csv('./datasets/M1-4-2.csv')

# 라벨 인코딩 (Object -> Int)
columns_to_encode = ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

for col in columns_to_encode:
    le = LabelEncoder()
    le.fit(df1[col])

    df1[col] = le.transform(df1[col])
    df2[col] = le.transform(df2[col])

# Churn 컬럼의 값에서 Yes -> 0, No -> 1로 매핑
df1['Churn'] = df1['Churn'].map({
    'No': 0,
    'Yes': 1
})

df2['Churn'] = df2['Churn'].map({
    'No': 0,
    'Yes': 1
})

# 자료형 변환
df1['Churn'] = df1['Churn'].astype('category')


# 독립 변수, 종속 변수 분리
x = df1.drop('Churn', axis=1)
y = df1['Churn']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestClassifier(n_estimators=300)
md.fit(x_train, y_train)

# 검증 데이터 평가
x_valid_encoded = pd.get_dummies(x_valid)
x_valid_encoded = x_valid_encoded.reindex(columns=x_encoded.columns, fill_value=0)

# 예측
pred_valid = md.predict(x_valid_encoded)

# 성능 평가
cm = confusion_matrix(pred_valid, y_valid)
print(cm)

print(accuracy_score(y_valid, pred_valid))
print(recall_score(y_valid, pred_valid))
print(precision_score(y_valid, pred_valid))
print(f1_score(y_valid, pred_valid))
print(roc_auc_score(y_valid, pred_valid))

# 테스트 데이터 평가
x_test = df2.drop('Churn', axis=1)

x_test_encoded = pd.get_dummies(x_test)   # 원-핫 인코딩
x_test_encoded = x_test_encoded.reindex(columns=x_encoded.columns, fill_value=0)

pred_new = md.predict(x_test_encoded)   # 예측
pred_new_label = ['No' if pred == 0 else 'Yes' for pred in pred_new]
print(pred_new)

# CSV 내보내기
result = pd.DataFrame({
    'pred': pred_new_label
})
print(result)

result.to_csv('./outputs/20240621_Q7.csv', index=False)

[[518 131]
 [ 59 136]]
0.7748815165876777
0.5093632958801498
0.6974358974358974
0.5887445887445888
0.7035551314756034
[0 0 1 ... 0 1 0]
     pred
0      No
1      No
2     Yes
3     Yes
4     Yes
...   ...
3652   No
3653   No
3654   No
3655  Yes
3656   No

[3657 rows x 1 columns]


### 문제 9 (연습)

In [303]:
import pandas as pd
from sklearn.ensemble import *
from sklearn.model_selection import *
from sklearn.metrics import *
from sklearn.preprocessing import *

df1 = pd.read_csv('./datasets/M2-4-1.csv')
df2 = pd.read_csv('./datasets/M2-4-2.csv')

# 독립 변수, 종속 변수 분할
x = df1.drop('mpg', axis=1)
y = df1['mpg']

# 원-핫 인코딩
x_encoded = pd.get_dummies(x)

# 데이터 분할
x_train, x_valid, y_train, y_valid = train_test_split(x_encoded, y, test_size=0.25)

# 모델링
md = RandomForestRegressor(n_estimators=300)
md.fit(x_train, y_train)

# 평가
pred = md.predict(x_valid)
result = mean_squared_error(y_valid, pred, squared=False)   # RMSE
print(result)

# 테스트 데이터 평가
x_test = df2

x_test_encoded = pd.get_dummies(x_test)   # 원-핫 인코딩

# 공통된 열 추출하기
common_features = list(set(x_encoded.columns).intersection(x_test_encoded.columns))

x_train_common = x_encoded[common_features]
x_test_common = x_test_encoded[common_features]

# 모델링 (한번 더)
md = RandomForestRegressor(n_estimators=300)
md.fit(x_train_common, y)

# 평가
pred = md.predict(x_test_common)
print(pred)

# CSV 내보내기
result = pd.DataFrame({
    'pred': pred
})
print(result)

result.to_csv('./outputs/20240621_Q8.csv', index=False)

c:\Users\kss34\anaconda3\envs\bigdata\Lib\site-packages\sklearn\metrics\_regression.py:483: FutureWarning: 'squared' is deprecated in version 1.4 and will be removed in 1.6. To calculate the root mean squared error, use the function'root_mean_squared_error'.
  warnings.warn(


1.6384596451816953
[14.62833333 32.24166667 30.44433333 33.82266667 21.52166667 15.51066667
 18.7        18.14333333 14.30133333 24.37266667 22.80066667 19.19066667
 17.80466667 16.4        17.276      15.205      10.442      10.4
 14.62833333 32.24166667 30.44433333 33.82266667 21.52166667 15.51066667
 18.7        18.14333333 14.30133333 24.37266667 22.80066667 19.19066667
 17.80466667 16.4        17.276      15.205      10.442      10.4
 14.62833333 32.24166667 30.44433333 33.82266667 21.52166667 15.51066667]
         pred
0   14.628333
1   32.241667
2   30.444333
3   33.822667
4   21.521667
5   15.510667
6   18.700000
7   18.143333
8   14.301333
9   24.372667
10  22.800667
11  19.190667
12  17.804667
13  16.400000
14  17.276000
15  15.205000
16  10.442000
17  10.400000
18  14.628333
19  32.241667
20  30.444333
21  33.822667
22  21.521667
23  15.510667
24  18.700000
25  18.143333
26  14.301333
27  24.372667
28  22.800667
29  19.190667
30  17.804667
31  16.400000
32  17.276000
33  15.

## 제3유형
---

### 문제 1 (23-6)

In [ ]:
import pandas as pd
from scipy.stats import chisquare

df = pd.read_csv('./datasets/P230605.csv', encoding='euckr')

# 코드별로 그룹화 및 비율 계산하여 컬럼 추가
df_placebo = df.groupby('코드').size().reset_index(name='건수')

total_count = len(df)
df_placebo['비율'] = df_placebo['건수'] / total_count

# (1) 위약 샘플 데이터가 '부작용 없음'인 데이터를 0~1 사이의 확률로 출력하기
answer1 = round(df_placebo['비율'][3], 3)
print(answer1)

# (2) 카이제곱 검정으로 검정 통계량 출력하기
df_rate = pd.DataFrame({
    '코드': [1, 2, 3, 4],
    '비율' : [0.05, 0.1, 0.05, 0.8]
})
result_chisquare = chisquare(df_placebo['건수'], f_exp=df_rate['비율'] * total_count)
print(result_chisquare)

answer2 = round(result_chisquare.statistic, 3)
print(answer2)

# (3) 유의 확률(p-value) 구하기
answer3 = round(result_chisquare.pvalue, 3)
print(answer3)

### 문제 2 (23-6)

In [305]:
import pandas as pd
import numpy as np
from scipy.stats import *
from sklearn.linear_model import LinearRegression

df = pd.read_csv('./datasets/P230606.csv', encoding='euckr')

x = df[['O3', 'Solar', 'Wind']]
y = df['Temperature']

lm = LinearRegression()
lm.fit(x, y)

coefs = pd.DataFrame({
    'Feature': ['O3', 'Solar', 'Wind'],
    'Coefficient': lm.coef_
})
print(coefs)

# (1) 오존농도 변수에 대한 회귀 계수 추정값 구하기
answer1 = round(float(coefs[coefs['Feature'] == 'O3']['Coefficient'].iloc[0]), 3)
print(answer1)

# (2) 오존농도, 일사량이 고정일 때 풍속이 증가함에 따라 온도가 낮아지는 것을 t-검증을 이용하여 유의 확률(p-value) 구하기
[statistic, p_value] = ttest_ind(x['Wind'], y)
answer2 = round(p_value, 3)
print(answer2)

# (3) 어떤 날이 오존농도 10, 일사량 90, 풍속 20일 때 온도의 예측값 구하기 
df_oneday = pd.DataFrame({
    'O3': [10],
    'Solar': [90],
    'Wind': [20]
})
answer3 = lm.predict(df_oneday)
answer3 = np.round(answer3[0], 3)
print(answer3)

  Feature  Coefficient
0      O3     0.171966
1   Solar     0.007276
2    Wind    -0.322945
0.172
0.0
68.334


### 문제3 (23-7)

In [306]:
import pandas as pd
import numpy as np
from scipy.stats import *
import statsmodels.api as sm

df = pd.read_csv('./datasets/P230705.csv')

# (1) 선형 관계 가장 큰 변수 찾아 상관 계수 구하기
corr_df = df.corr()
target = corr_df['Target']
answer1 = target.sort_values(ascending=False)[1]
print(answer1)

# (2) Target 변수를 종속 변수로 하여 다중 선형 회귀 모델링을 진행했을 때 v2 컬럼의 회귀 계수 구하기

x = df.drop('Target', axis=1)   # 독립 변수
x = sm.add_constant(x)   # 상수항 추가
y = df['Target']   # 종속 변수

## OLS는 "Ordinary Least Squares"의 약자로, 선형 회귀 분석 방법 중 하나이다. statsmodels.api의 일부로서, OLS 클래스를 사용하여 선형 회귀 모델을 정의할 수 있다.
md = sm.OLS(y, x).fit()

answer2 = md.params['v2']
print(answer2)

# (3) 회귀 계수들이 가지는 p-값들 중 최대값 구하기
answer3 = md.pvalues.max()
print(answer3)

0.6270251925517436
6.440301364843059
0.9265545986907169


C:\Users\kss34\AppData\Local\Temp\ipykernel_16588\1648393551.py:11: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  answer1 = target.sort_values(ascending=False)[1]


### 문제 4 (23-7)

In [307]:
import numpy as np
import pandas as pd
from scipy.stats import *
import statsmodels.api as sm

from sklearn.metrics import accuracy_score

df = pd.read_csv('./datasets/P230706.csv')

train_data = df[:210].reset_index(drop=True)
test_data = df[210:].reset_index(drop=True)

# (1) train 데이터로 target을 종속 변수로 로지스틱 회귀를 진행할 때, age 컬럼의 오즈비 구하기
x = train_data.drop('target', axis=1)   # 독립 변수
y = train_data['target']   # 종속 변수

md1 = sm.Logit(y, x).fit()

answer1 = np.exp(md1.params['age'])
print(answer1)

# (2) train 데이터로 로지스틱 회귀를 진행했을 경우 잔차 이탈도 계산하기
md2 = sm.GLM(y, x, family=sm.families.Binomial()).fit()

answer2 = md2.deviance
print(answer2)

# (3) train 데이터로 로지스틱 회귀를 진행했을 경우 로짓 우도값 도출하기
answer3 = md1.llf
print(answer3)

# (4) test 데이터의 독립변수로 target 예측 후 오류율 구하기
data = test_data.drop('target', axis=1)
pred = md1.predict(data)

pred = (pred > 0.5).astype('int')
target = test_data['target']
answer3 = 1 - accuracy_score(target, pred)
print(answer3)

Optimization terminated successfully.
         Current function value: 0.343347
         Iterations 7
0.9562078844664191
144.205620063278
-72.102810031639
0.1954022988505747


### 문제 5 (시험장 예제)

In [308]:
import numpy as np
import pandas as pd
from scipy.stats import *
import statsmodels.api as sm
from statsmodels.formula.api import logit

df = pd.read_csv('./datasets/titanic.csv')

# (1) Gender와 Survived 변수 간의 독립성 검정을 실시하였을 때, 카이제곱 통계량 구하기
table =pd.crosstab(df['Gender'], df['Survived'])
chi2, pvalue, dof, exp = chi2_contingency(table)   # 독립성 검정
answer1 = round(chi2, 3)
print(answer1, "/ p-value", pvalue)   # 유의 수준(0.5)보다 작으므로 대립가설 채택 (서로 독립)

# (2) Gender, SibSp, Parch, Fare를 독립 변수로 사용하여 로지스틱 회귀 모형을 실시하였을 때, Parch 변수의 계수값 구하기
answer2 = logit('Survived ~ Gender+SibSp+Parch+Fare', data=df).fit().summary()
print(answer2)   # Parch 변수의 coef 값 확인 (-0.2007)

# (3) SibSp 변수가 한 단위 증가할 때 생존할 오즈비 값 구하기
result = logit('Survived ~ Gender+SibSp+Parch+Fare', data=df).fit().params
print(result)
answer3 = round(np.exp(result['SibSp']), 3)
print(answer3)   # 0.702

260.717 / p-value 1.1973570627755645e-58
Optimization terminated successfully.
         Current function value: 0.482065
         Iterations 6
                           Logit Regression Results                           
Dep. Variable:               Survived   No. Observations:                  891
Model:                          Logit   Df Residuals:                      886
Method:                           MLE   Df Model:                            4
Date:                Fri, 21 Jun 2024   Pseudo R-squ.:                  0.2761
Time:                        19:41:56   Log-Likelihood:                -429.52
converged:                       True   LL-Null:                       -593.33
Covariance Type:            nonrobust   LLR p-value:                 1.192e-69
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept          0.9466      0.169      5.590      0.000 